; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags = 
  -std=gnu++17
  -D CATFEEDER_VERSION=\"0.9.3\" 
  -D USE_NTP
;  -D DEBUG_STALLGUARD 
;  -D DEBUG_WEBSERVER_API
;  -D DEBUG_FILLSENSOR
;  -D DEBUG_TIMESOURCE
build_unflag = 
  -std=gnu++11
monitor_filters = esp32_exception_decoder
extra_scripts = pre:gzip_embeds.py
board_build.partitions = min_spiffs.csv
board_build.embed_txtfiles = 
  data/style.css.gz
  data/index.html
  data/timers.html
  data/settings.html
  data/debuglogs.html
  data/firmware.html
  data/logs.html
  data/fillsensorsettings.html
  data/motorsettings.html
  data/networksettings.html
  data/networkchanged.html
  data/timesettings.html
  data/reset.html
  data/favicon.ico.gz
  data/logo.svg.gz
lib_ldf_mode=deep
lib_deps = 
	esp32async/ESPAsyncWebServer@^3.8.1
	teemuatlut/TMCStepper@^0.7.3
	adafruit/Adafruit SSD1306@^2.5.9
	adafruit/Adafruit_VL53L0X@^1.2.4
	bblanchon/ArduinoJson@^7.4.2
	janelia-arduino/TMC2209@^10.1.1
	gin66/FastAccelStepper@^0.33.9
