name: Alfeedo ESP32 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PlatformIO
      # You may pin to the exact commit or the version.
      # uses: n-vr/setup-platformio-action@ef5952e6a4d30c219158b781a84d31b018549c20
      uses: n-vr/setup-platformio-action@v1.0.1
      with:
        # PlatformIO version to use. (e.g. 5.2.5, 5.2 or 5
        platformio-version: 6.1.19 # optional, default is newest

    - name: Build
      run: platformio run
